@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Dec 31 18:34:17 +0100 2017
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim AddressDecoderTB_BD_wrapper_behav -key {Behavioral:AddressDecoderTB:Functional:AddressDecoderTB_BD_wrapper} -tclbatch AddressDecoderTB_BD_wrapper.tcl -view D:/BakkArbeit/git/VivadoProject2/AddressDecoderTB_BD_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
