# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/BakkArbeit/git/VivadoProject/BakkArbeit/BakkArbeit.srcs/sources_1/bd/BakkArbeit_Blockdesign/ip/BakkArbeit_Blockdesign_processing_system7_0_0/BakkArbeit_Blockdesign_processing_system7_0_0.xci
# IP: The module: 'BakkArbeit_Blockdesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/BakkArbeit/git/VivadoProject/BakkArbeit/BakkArbeit.srcs/sources_1/bd/BakkArbeit_Blockdesign/ip/BakkArbeit_Blockdesign_processing_system7_0_0/BakkArbeit_Blockdesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BakkArbeit_Blockdesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/BakkArbeit/git/VivadoProject/BakkArbeit/BakkArbeit.srcs/sources_1/bd/BakkArbeit_Blockdesign/ip/BakkArbeit_Blockdesign_processing_system7_0_0/BakkArbeit_Blockdesign_processing_system7_0_0.xci
# IP: The module: 'BakkArbeit_Blockdesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/BakkArbeit/git/VivadoProject/BakkArbeit/BakkArbeit.srcs/sources_1/bd/BakkArbeit_Blockdesign/ip/BakkArbeit_Blockdesign_processing_system7_0_0/BakkArbeit_Blockdesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BakkArbeit_Blockdesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
