@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jan 04 22:24:47 +0100 2018
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim PicoRV32_BD_wrapper_behav -key {Behavioral:Complete_design:Functional:PicoRV32_BD_wrapper} -tclbatch PicoRV32_BD_wrapper.tcl -view D:/BakkArbeit/git/VivadoProject2/BakkArbeit2.srcs/Complete_design/imports/VivadoProject2/PicoRV32_BD_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
