# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/PicoRV32_BD/PicoRV32_BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PicoRV32_BD || ORIG_REF_NAME==PicoRV32_BD} -quiet] -quiet

# IP: bd/PicoRV32_BD/ip/PicoRV32_BD_picorv32_0_0/PicoRV32_BD_picorv32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PicoRV32_BD_picorv32_0_0 || ORIG_REF_NAME==PicoRV32_BD_picorv32_0_0} -quiet] -quiet

# IP: bd/PicoRV32_BD/ip/PicoRV32_BD_Address_Decoder_0_0/PicoRV32_BD_Address_Decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PicoRV32_BD_Address_Decoder_0_0 || ORIG_REF_NAME==PicoRV32_BD_Address_Decoder_0_0} -quiet] -quiet

# IP: bd/PicoRV32_BD/ip/PicoRV32_BD_processing_system7_0_0/PicoRV32_BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PicoRV32_BD_processing_system7_0_0 || ORIG_REF_NAME==PicoRV32_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/PicoRV32_BD/ip/PicoRV32_BD_Out_bank_0_0/PicoRV32_BD_Out_bank_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PicoRV32_BD_Out_bank_0_0 || ORIG_REF_NAME==PicoRV32_BD_Out_bank_0_0} -quiet] -quiet

# IP: bd/PicoRV32_BD/ip/PicoRV32_BD_Memory_0_0/PicoRV32_BD_Memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PicoRV32_BD_Memory_0_0 || ORIG_REF_NAME==PicoRV32_BD_Memory_0_0} -quiet] -quiet

# IP: bd/PicoRV32_BD/ip/PicoRV32_BD_complete_design_TB_0_0/PicoRV32_BD_complete_design_TB_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PicoRV32_BD_complete_design_TB_0_0 || ORIG_REF_NAME==PicoRV32_BD_complete_design_TB_0_0} -quiet] -quiet

# XDC: bd/PicoRV32_BD/PicoRV32_BD_ooc.xdc
