# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/BakkArbeit_Blockdesign/BakkArbeit_Blockdesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BakkArbeit_Blockdesign || ORIG_REF_NAME==BakkArbeit_Blockdesign} -quiet] -quiet

# IP: bd/BakkArbeit_Blockdesign/ip/BakkArbeit_Blockdesign_processing_system7_0_0/BakkArbeit_Blockdesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BakkArbeit_Blockdesign_processing_system7_0_0 || ORIG_REF_NAME==BakkArbeit_Blockdesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/BakkArbeit_Blockdesign/ip/BakkArbeit_Blockdesign_UART_datagenerator_0_0/BakkArbeit_Blockdesign_UART_datagenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BakkArbeit_Blockdesign_UART_datagenerator_0_0 || ORIG_REF_NAME==BakkArbeit_Blockdesign_UART_datagenerator_0_0} -quiet] -quiet

# XDC: bd/BakkArbeit_Blockdesign/BakkArbeit_Blockdesign_ooc.xdc
