# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/constrs_1/new/picorv32_axi.xdc

# Block Designs: D:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: D:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_picorv32_axi_0_0/design_1_picorv32_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_picorv32_axi_0_0 || ORIG_REF_NAME==design_1_picorv32_axi_0_0}]

# IP: D:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_2 || ORIG_REF_NAME==design_1_blk_mem_gen_0_2}]

# IP: D:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0}]

# IP: d:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: d:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_UART_datagenerator_0_0/design_1_UART_datagenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UART_datagenerator_0_0 || ORIG_REF_NAME==design_1_UART_datagenerator_0_0}]

# XDC: d:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2_ooc.xdc

# XDC: d:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc

# XDC: d:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: D:/Dropbox/Studium/Bakk Arbeit/VivadoProject/PicroRV/PicroRV.srcs/sources_1/bd/design_1/design_1_ooc.xdc
